require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'BTrend' do
  config = use_native_modules!
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'GoogleSignIn', '~> 6.0.2'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'BTrendTests' do
    inherit! :complete
    # Pods for testing
  end

end