//This file has all the constatns array you'll need throughout the app

export const GendersArr = [
    "Female",
    "Male",
    "Agender",
    "Androgyne",
    "Androgynous",
    "Bigender",
    "Cis",
    "Cisgender",
    "Cis Female",
    "Cis Male",
    "Cis Man",
    "Cis Woman",
    "Cisgender Female",
    "Cisgender Male",
    "Cisgender Man",
    "Cisgender Woman",
    "FTM",
    "Gender Fluid",
    "Gender Nonconforming",
    "Gender Questioning",
    "Gender Variant",
    "Genderqueer",
    "Intersex",
    "MTF",
    "Neither",
    "Neutrois",
    "Non-binary",
    "Other",
    "Pangender",
    "Trans",
    "Trans Female",
    "Trans Male",
    "Trans Man",
    "Trans Person",
    "Trans Woman",
    "Transfeminine",
    "Transgender",
    "Transgender Female",
    "Transgender Male",
    "Transgender Man",
    "Transgender Person",
    "Transgender Woman",
    "Transmasculine",
    "Transsexual",
    "Transsexual Female",
    "Transsexual Male",
    "Transsexual Man",
    "Transsexual Person",
    "Transsexual Woman",
    "Two-Spirit",
];

export const Language = [

    "English",
    "Hindi",
    "Mandarin",
    "Spanish",
    "French",
    "Arabic",
    "Bengali",
    "Russian",
    "Portuguese",
    "Indonesian"

]
export const filterOpts = [
    "Latest",
    "Archived",
    "Active",
    "Paused",
    "Closed"
]

export const CategoriesArr = [
    "Beauty",
    "Fashion Photography",
    "Fashion",
    "Makeup Artist",
    "Travel",
    "Liefestyle",
    "Sports",
    "Beauty Artist",
    "Manucures",
    "Fashion Modeling",
    "Food",
    "Travel & Tourism",
    "Foodies",
    "Health & Fitness",
    "Yoga",
    "Pets Animals",
    "Parenting",
    "Photographers",
    "Babies", "Luxury", "Plastic surgery", "Garners", "Film and television",
    , "Events", "Working Online", "Wedding", "Medical", "Restaurants", "Family", "Companies and business", "Art", "Technology", "Gastronomy", "Personal",
    , "Models", "Internet", "Crypto", "Entertainment", "Leisure", "Parties", "Hobbies",
    "Design", "Home", "Society", "Games", "Humor and comedy", "Sciences", "Music",
    "Culture", "Marketing", "Cars", "Gadgets", "Motivational speaker",
    "Business", "Decoration", "Ecology", "Nature and environment",
    "Shopping", "Animals", "Audiovisual", "Video games", "Videos", "Celebrity",
    "Aesthetic", "Wellness", "Artist", "Religion and philosophy", "Politics",
    "Charity", "Books", "Bloggers & Vloggers", "Education", "Sexuality", "Relationship", "TV shows", "Others"
]

//Array of the countries where you'll only show Male and female as genders
export const conservativeCountries = [
    "EG",
    "UAE",
    "BH",
    "DZ",
    "COM",
    "LY",
    "LB",
    "DJ",
    "IQ",
    "KW",
    "JO",
    "MR",
    "PS",
    "MA",
    "OM",
    "QA",
    "SA",
    "SO",
    "SD",
    "SY",
    "YE",
    "TN",
]

export const LanguagesArr = [
    "English",
    "French",
    "Arabic"
]